# Cloudflare Workers configuration for Dendrites (Edge Cache)
# Simple edge caching and request routing

name = "synapse-dendrites"
main = "src/index.js"
compatibility_date = "2024-01-08"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
ENVIRONMENT = "production"
SYNAPSE_HUB_URL = "https://synapse-central-hub.onrender.com"
LOG_LEVEL = "INFO"
DENDRITES_API_KEY = "dendrites_7f3a9b2e5c8d1f4a6b9c2e5f8a1b4e7c"

# KV Namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "c7467f9d479f4b5e9eaf0c1dc8746a89"

# Resource limits removed for free tier compatibility